name: Boardgame CI-CD

on:
push:
branches:
- main

env:
IMAGE_NAME: sireeshahub1802/board

jobs:
build-deploy:
runs-on: ubuntu-latest

steps:
  - name: Checkout Source
    uses: actions/checkout@v4

  - name: Setup Java
    uses: actions/setup-java@v4
    with:
      distribution: temurin
      java-version: '17'

  - name: Build Application
    run: mvn clean package
